export type UserRole = 'SUPERADMIN' | 'ADMIN_HR' | 'SUPERVISOR' | 'EMPLOYEE';

const PRODUCTION_ADMIN_ROLES: readonly UserRole[] = ['SUPERADMIN'];
const PRODUCTION_EMPLOYEE_ROLES: readonly UserRole[] = ['EMPLOYEE'];
const PRODUCTION_ALL_ROLES: readonly UserRole[] = ['SUPERADMIN', 'EMPLOYEE'];

export const PERMISSIONS: Record<string, readonly UserRole[]> = {
  USER_CREATE: PRODUCTION_ADMIN_ROLES,
  USER_READ: PRODUCTION_ADMIN_ROLES,
  USER_UPDATE: PRODUCTION_ADMIN_ROLES,
  USER_DELETE: PRODUCTION_ADMIN_ROLES,

  EMPLOYEE_CREATE: PRODUCTION_ADMIN_ROLES,
  EMPLOYEE_READ: PRODUCTION_ADMIN_ROLES,
  EMPLOYEE_UPDATE: PRODUCTION_ADMIN_ROLES,
  EMPLOYEE_DELETE: PRODUCTION_ADMIN_ROLES,
  EMPLOYEE_READ_OWN: PRODUCTION_EMPLOYEE_ROLES,

  LOCATION_CREATE: PRODUCTION_ADMIN_ROLES,
  LOCATION_READ: PRODUCTION_ADMIN_ROLES,
  LOCATION_UPDATE: PRODUCTION_ADMIN_ROLES,
  LOCATION_DELETE: PRODUCTION_ADMIN_ROLES,

  SHIFT_CREATE: PRODUCTION_ADMIN_ROLES,
  SHIFT_READ: PRODUCTION_ADMIN_ROLES,
  SHIFT_UPDATE: PRODUCTION_ADMIN_ROLES,
  SHIFT_DELETE: PRODUCTION_ADMIN_ROLES,

  ATTENDANCE_CREATE: PRODUCTION_ALL_ROLES,
  ATTENDANCE_READ: PRODUCTION_ADMIN_ROLES,
  ATTENDANCE_READ_OWN: PRODUCTION_EMPLOYEE_ROLES,
  ATTENDANCE_UPDATE: PRODUCTION_ADMIN_ROLES,
  ATTENDANCE_DELETE: PRODUCTION_ADMIN_ROLES,
  ATTENDANCE_MANUAL_ADJUST: PRODUCTION_ADMIN_ROLES,

  LEAVE_CREATE: PRODUCTION_EMPLOYEE_ROLES,
  LEAVE_READ: PRODUCTION_ADMIN_ROLES,
  LEAVE_READ_OWN: PRODUCTION_EMPLOYEE_ROLES,
  LEAVE_APPROVE: PRODUCTION_ADMIN_ROLES,
  LEAVE_REJECT: PRODUCTION_ADMIN_ROLES,

  KPI_TEMPLATE_CREATE: PRODUCTION_ADMIN_ROLES,
  KPI_TEMPLATE_READ: PRODUCTION_ADMIN_ROLES,
  KPI_TEMPLATE_UPDATE: PRODUCTION_ADMIN_ROLES,
  KPI_TEMPLATE_DELETE: PRODUCTION_ADMIN_ROLES,
  KPI_ASSIGN: PRODUCTION_ADMIN_ROLES,
  KPI_INPUT: PRODUCTION_ADMIN_ROLES,
  KPI_READ: PRODUCTION_ADMIN_ROLES,
  KPI_READ_OWN: PRODUCTION_EMPLOYEE_ROLES,
  KPI_APPROVE: PRODUCTION_ADMIN_ROLES,

  REPORT_VIEW: PRODUCTION_ADMIN_ROLES,
  REPORT_EXPORT: PRODUCTION_ADMIN_ROLES,

  PAYROLL_READ: PRODUCTION_ADMIN_ROLES,
  PAYROLL_READ_OWN: PRODUCTION_EMPLOYEE_ROLES,
  PAYROLL_MUTATE: PRODUCTION_ADMIN_ROLES,
  PAYROLL_APPROVE: PRODUCTION_ADMIN_ROLES,
  PAYROLL_PAY: PRODUCTION_ADMIN_ROLES,
  PAYROLL_EXPORT: PRODUCTION_ADMIN_ROLES,

  DASHBOARD_SUPERADMIN: PRODUCTION_ADMIN_ROLES,
  DASHBOARD_HR: [],
  DASHBOARD_SUPERVISOR: [],
  DASHBOARD_EMPLOYEE: PRODUCTION_EMPLOYEE_ROLES,

  AUDIT_READ: PRODUCTION_ADMIN_ROLES,
  NOTIFICATION_READ_OWN: PRODUCTION_ALL_ROLES,
} as const;

export type Permission = keyof typeof PERMISSIONS;

const ROLE_RANK: Record<UserRole, number> = {
  EMPLOYEE: 1,
  SUPERVISOR: 0,
  ADMIN_HR: 0,
  SUPERADMIN: 2,
};

export function canManageRole(actorRole: UserRole, targetRole: UserRole): boolean {
  return actorRole === 'SUPERADMIN' && (targetRole === 'SUPERADMIN' || targetRole === 'EMPLOYEE');
}

export function hasPermission(userRole: UserRole, permission: Permission): boolean {
  const allowedRoles = PERMISSIONS[permission];
  return allowedRoles.includes(userRole);
}

export function requirePermission(userRole: UserRole, permission: Permission): void {
  if (!hasPermission(userRole, permission)) {
    throw new Error(`Unauthorized: Missing permission ${permission}`);
  }
}

export function canAccessOwnData(userRole: UserRole, userId: string, targetUserId: string): boolean {
  const fullAccessRoles: readonly UserRole[] = ['SUPERADMIN'];

  if (fullAccessRoles.includes(userRole)) {
    return true;
  }
  
  // Others can only access their own data
  return userId === targetUserId;
}

export function canAccessTeamData(
  userRole: UserRole,
  userId: string,
  targetUserId: string,
  supervisorId?: string
): boolean {
  const fullAccessRoles: readonly UserRole[] = ['SUPERADMIN'];

  if (fullAccessRoles.includes(userRole)) {
    return true;
  }
  
  // Can access own data
  return userId === targetUserId;
}
