import { and, asc, count, desc, eq, gte, lte, sql, sum } from 'drizzle-orm';
import { db, attendances, employees, kpiResults, payrollRuns } from '@/lib/db';
import type { UserRole } from '@/lib/permissions';

export type PdfReportType = 'attendance_summary' | 'kpi_performance' | 'payroll_summary' | 'executive_hr';

export interface PdfReportRequest {
  reportType: PdfReportType;
  from?: string;
  to?: string;
  division?: string;
}

export interface PdfChart {
  title: string;
  labels: string[];
  values: number[];
}

export interface PdfTable {
  title: string;
  columns: string[];
  rows: string[][];
}

export interface PdfDocumentInput {
  title: string;
  reportType: PdfReportType;
  generatedBy: string;
  generatedAt: Date;
  periodLabel: string;
  filters: string;
  summaryCards: { label: string; value: string }[];
  charts: PdfChart[];
  tables: PdfTable[];
}

const REPORT_TITLES: Record<PdfReportType, string> = {
  attendance_summary: 'Attendance Summary PDF',
  kpi_performance: 'KPI Performance PDF',
  payroll_summary: 'Payroll Summary PDF',
  executive_hr: 'Executive HR PDF',
};

const SELFIE_FIELD_PATTERN = /selfie/i;

export function assertPdfReportAccess(role: UserRole) {
  if (role !== 'SUPERADMIN') throw new Error('PDF_REPORT_FORBIDDEN');
}

export function getPdfReportMaxRows() {
  const parsed = Number(process.env.PDF_REPORT_MAX_ROWS || '1000');
  if (!Number.isFinite(parsed) || parsed < 1) return 1000;
  return Math.min(Math.floor(parsed), 5000);
}

export function defaultCurrentMonthRange(now = new Date()) {
  const from = new Date(now.getFullYear(), now.getMonth(), 1);
  const to = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59, 999);
  return { from, to };
}

export function getPdfReportMaxDateRangeMonths() {
  const parsed = Number(process.env.PDF_REPORT_MAX_DATE_RANGE_MONTHS || '12');
  if (!Number.isFinite(parsed) || parsed < 1) return 12;
  return Math.min(Math.floor(parsed), 24);
}

export function validatePdfDateRange(fromInput?: string, toInput?: string) {
  const defaults = defaultCurrentMonthRange();
  const from = fromInput ? new Date(`${fromInput}T00:00:00.000Z`) : defaults.from;
  const to = toInput ? new Date(`${toInput}T23:59:59.999Z`) : defaults.to;

  if (Number.isNaN(from.getTime()) || Number.isNaN(to.getTime())) {
    throw new Error('Tanggal laporan tidak valid');
  }

  if (to < from) {
    throw new Error('Tanggal akhir tidak boleh sebelum tanggal awal');
  }

  const maxRangeMonths = getPdfReportMaxDateRangeMonths();
  const maxRangeTo = new Date(from);
  maxRangeTo.setMonth(maxRangeTo.getMonth() + maxRangeMonths);
  if (to > maxRangeTo) {
    throw new Error(`Rentang PDF maksimal ${maxRangeMonths} bulan`);
  }

  return { from, to };
}

export function removeSelfieFields<T>(value: T): T {
  if (Array.isArray(value)) return value.map((entry) => removeSelfieFields(entry)) as T;
  if (value instanceof Date) return value;
  if (!value || typeof value !== 'object') return value;

  const clean: Record<string, unknown> = {};
  for (const [key, entry] of Object.entries(value as Record<string, unknown>)) {
    if (SELFIE_FIELD_PATTERN.test(key)) continue;
    clean[key] = removeSelfieFields(entry);
  }
  return clean as T;
}

function escapePdfText(value: unknown) {
  return String(value ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
    .replace(/[\r\n]+/g, ' ')
    .slice(0, 140);
}

function money(value: number) {
  return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value || 0);
}

function formatDate(date: Date) {
  return date.toISOString().slice(0, 10);
}

function objectLine(text: string, x: number, y: number, size = 9, font = 'F1') {
  return `BT /${font} ${size} Tf ${x} ${y} Td (${escapePdfText(text)}) Tj ET`;
}

function rect(x: number, y: number, width: number, height: number, color = '0.95 0.95 0.95') {
  return `q ${color} rg ${x} ${y} ${width} ${height} re f Q`;
}

export function buildPdfDocument(input: PdfDocumentInput): Uint8Array {
  const lines: string[] = [];
  let y = 790;
  const next = (gap = 14) => { y -= gap; return y; };

  lines.push(rect(0, 770, 595, 72, '1 0.757 0.027'));
  lines.push(objectLine('MyProdusen', 36, 810, 22, 'F2'));
  lines.push(objectLine('Sistem Internal Produsen Dimsum Medan', 36, 792, 9));
  lines.push(objectLine(input.title, 330, 810, 14, 'F2'));
  lines.push(objectLine(`Generated by: ${input.generatedBy}`, 330, 792, 8));
  lines.push(objectLine(`Generated at: ${input.generatedAt.toISOString()}`, 330, 780, 8));

  y = 748;
  lines.push(objectLine(`Period: ${input.periodLabel}`, 36, y, 10, 'F2'));
  lines.push(objectLine(`Filters: ${input.filters}`, 36, next(), 9));
  lines.push(objectLine('CONFIDENTIAL - Internal MyProdusen / TBM Group use only', 36, next(), 9, 'F2'));

  const cardWidth = 124;
  input.summaryCards.slice(0, 4).forEach((card, index) => {
    const x = 36 + index * (cardWidth + 10);
    lines.push(rect(x, y - 70, cardWidth, 46, '0.965 0.965 0.965'));
    lines.push(objectLine(card.label, x + 8, y - 42, 8));
    lines.push(objectLine(card.value, x + 8, y - 60, 13, 'F2'));
  });
  y -= 98;

  input.charts.slice(0, 5).forEach((chart) => {
    lines.push(objectLine(chart.title, 36, y, 11, 'F2'));
    const max = Math.max(...chart.values, 1);
    chart.labels.slice(0, 8).forEach((label, index) => {
      const value = chart.values[index] ?? 0;
      const barWidth = Math.max(4, (value / max) * 180);
      const rowY = y - 18 - index * 15;
      lines.push(objectLine(label, 48, rowY, 8));
      lines.push(rect(150, rowY - 3, barWidth, 8, index % 2 === 0 ? '1 0.757 0.027' : '0.898 0.224 0.208'));
      lines.push(objectLine(String(value), 340, rowY, 8));
    });
    y -= 150;
    if (y < 220) y = 220;
  });

  input.tables.slice(0, 4).forEach((table) => {
    lines.push(objectLine(table.title, 36, y, 11, 'F2'));
    y -= 16;
    lines.push(rect(36, y - 4, 520, 18, '0.93 0.93 0.93'));
    table.columns.slice(0, 6).forEach((column, index) => lines.push(objectLine(column, 44 + index * 84, y, 8, 'F2')));
    y -= 18;
    table.rows.slice(0, 14).forEach((row) => {
      row.slice(0, 6).forEach((cell, index) => lines.push(objectLine(cell, 44 + index * 84, y, 7)));
      y -= 14;
    });
    y -= 14;
    if (y < 110) y = 110;
  });

  lines.push(objectLine('TBM Group', 36, 44, 9, 'F2'));
  lines.push(objectLine('Page 1 of 1', 500, 44, 8));

  const content = lines.join('\n');
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>',
    `<< /Length ${Buffer.byteLength(content, 'latin1')} >>\nstream\n${content}\nendstream`,
  ];

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(pdf, 'latin1'));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = Buffer.byteLength(pdf, 'latin1');
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => { pdf += `${String(offset).padStart(10, '0')} 00000 n \n`; });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return new Uint8Array(Buffer.from(pdf, 'latin1'));
}

async function attendanceData(from: Date, to: Date, maxRows: number, division?: string) {
  const filters = [gte(attendances.checkInTime, from), lte(attendances.checkInTime, to)];
  if (division) filters.push(eq(employees.division, division));

  const rows = await db
    .select({
      date: attendances.checkInTime,
      status: attendances.status,
      employeeName: employees.fullName,
      nip: employees.nip,
      division: employees.division,
      lateMinutes: attendances.lateMinutes,
      totalWorkMinutes: attendances.totalWorkMinutes,
    })
    .from(attendances)
    .innerJoin(employees, eq(attendances.employeeId, employees.id))
    .where(and(...filters))
    .orderBy(desc(attendances.checkInTime))
    .limit(maxRows);

  const byStatus = rows.reduce<Record<string, number>>((acc, row) => {
    acc[row.status] = (acc[row.status] ?? 0) + 1;
    return acc;
  }, {});

  const trend = rows.reduce<Record<string, number>>((acc, row) => {
    const key = row.date.toISOString().slice(0, 10);
    acc[key] = (acc[key] ?? 0) + 1;
    return acc;
  }, {});

  return {
    rows,
    byStatus,
    trend,
    summary: [
      { label: 'Total Attendance', value: String(rows.length) },
      { label: 'Present', value: String(byStatus.PRESENT ?? 0) },
      { label: 'Late', value: String(byStatus.LATE ?? 0) },
      { label: 'Absent', value: String(byStatus.ABSENT ?? 0) },
    ],
  };
}

async function kpiData(from: Date, to: Date, maxRows: number, division?: string) {
  const fromPeriod = from.toISOString().slice(0, 7);
  const toPeriod = to.toISOString().slice(0, 7);
  const filters = [gte(kpiResults.period, fromPeriod), lte(kpiResults.period, toPeriod)];
  if (division) filters.push(eq(employees.division, division));

  const rows = await db
    .select({ employeeName: employees.fullName, nip: employees.nip, division: employees.division, period: kpiResults.period, score: kpiResults.score, approved: kpiResults.isApproved })
    .from(kpiResults)
    .innerJoin(employees, eq(kpiResults.employeeId, employees.id))
    .where(and(...filters))
    .orderBy(desc(kpiResults.period))
    .limit(maxRows);

  const byDivision = rows.reduce<Record<string, number[]>>((acc, row) => {
    const key = row.division || 'Tanpa Divisi';
    acc[key] = [...(acc[key] ?? []), row.score];
    return acc;
  }, {});
  const average = rows.length ? rows.reduce((sum, row) => sum + row.score, 0) / rows.length : 0;

  return {
    rows,
    byDivision,
    summary: [
      { label: 'KPI Rows', value: String(rows.length) },
      { label: 'Average Score', value: average.toFixed(1) },
      { label: 'Approved', value: String(rows.filter((row) => row.approved).length) },
      { label: 'Pending', value: String(rows.filter((row) => !row.approved).length) },
    ],
  };
}

async function payrollData(from: Date, to: Date, maxRows: number) {
  const runs = await db
    .select()
    .from(payrollRuns)
    .where(and(gte(payrollRuns.periodStart, from), lte(payrollRuns.periodEnd, to)))
    .orderBy(desc(payrollRuns.period))
    .limit(maxRows);

  const paid = runs.filter((run) => run.status === 'PAID').length;
  const pending = runs.length - paid;
  return {
    runs,
    summary: [
      { label: 'Payroll Runs', value: String(runs.length) },
      { label: 'Paid', value: String(paid) },
      { label: 'Pending', value: String(pending) },
      { label: 'Net Pay', value: money(runs.reduce((sum, run) => sum + run.totalNetPay, 0)) },
    ],
  };
}

export async function buildPdfReportData(request: PdfReportRequest, generatedBy: string) {
  const { from, to } = validatePdfDateRange(request.from, request.to);
  const maxRows = getPdfReportMaxRows();
  const periodLabel = `${formatDate(from)} sampai ${formatDate(to)}`;
  const filters = `Divisi: ${request.division || 'Semua'}; Max rows: ${maxRows}`;
  const attendance = await attendanceData(from, to, maxRows, request.division);
  const kpi = await kpiData(from, to, maxRows, request.division);
  const payroll = await payrollData(from, to, maxRows);

  const summaryByType: Record<PdfReportType, { label: string; value: string }[]> = {
    attendance_summary: attendance.summary,
    kpi_performance: kpi.summary,
    payroll_summary: payroll.summary,
    executive_hr: [
      { label: 'Employees in Attendance', value: String(new Set(attendance.rows.map((row) => row.nip)).size) },
      { label: 'Attendance Rows', value: String(attendance.rows.length) },
      { label: 'Avg KPI', value: kpi.summary[1].value },
      { label: 'Payroll Net', value: payroll.summary[3].value },
    ],
  };

  const kpiDivisionEntries = Object.entries(kpi.byDivision).map(([label, scores]) => ({
    label,
    value: scores.length ? scores.reduce((sum, score) => sum + score, 0) / scores.length : 0,
  }));

  const charts: PdfChart[] = [
    { title: 'attendance status chart', labels: Object.keys(attendance.byStatus), values: Object.values(attendance.byStatus) },
    { title: 'attendance trend chart', labels: Object.keys(attendance.trend).slice(-8), values: Object.values(attendance.trend).slice(-8) },
    { title: 'KPI by division chart', labels: kpiDivisionEntries.map((entry) => entry.label), values: kpiDivisionEntries.map((entry) => Number(entry.value.toFixed(1))) },
    { title: 'payroll paid/pending chart', labels: ['PAID', 'PENDING'], values: [payroll.summary[1].value, payroll.summary[2].value].map(Number) },
    { title: 'gross/deduction/net chart', labels: ['Gross', 'Deduction', 'Net'], values: [
      payroll.runs.reduce((sum, run) => sum + run.totalGrossPay, 0),
      payroll.runs.reduce((sum, run) => sum + run.totalDeductions, 0),
      payroll.runs.reduce((sum, run) => sum + run.totalNetPay, 0),
    ] },
  ];

  const tables: PdfTable[] = [
    {
      title: 'Attendance Summary',
      columns: ['Date', 'NIP', 'Name', 'Division', 'Status', 'Late'],
      rows: attendance.rows.map((row) => [formatDate(row.date), row.nip, row.employeeName, row.division || '', row.status, String(row.lateMinutes)]),
    },
    {
      title: 'KPI Performance',
      columns: ['Period', 'NIP', 'Name', 'Division', 'Score', 'Approved'],
      rows: kpi.rows.map((row) => [row.period, row.nip, row.employeeName, row.division || '', row.score.toFixed(1), row.approved ? 'YES' : 'NO']),
    },
    {
      title: 'Payroll Summary',
      columns: ['Period', 'Status', 'Employees', 'Gross', 'Deduct', 'Net'],
      rows: payroll.runs.map((run) => [run.period, run.status, String(run.totalEmployees), money(run.totalGrossPay), money(run.totalDeductions), money(run.totalNetPay)]),
    },
  ];

  return removeSelfieFields({
    title: REPORT_TITLES[request.reportType],
    reportType: request.reportType,
    generatedBy,
    generatedAt: new Date(),
    periodLabel,
    filters,
    summaryCards: summaryByType[request.reportType],
    charts,
    tables,
  });
}
